name: rst
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - fftw
  - furo
  - gcc_linux-64
  - gsl
  - h5py
  - llvm-openmp
  - mock
  - numpy
  - pillow
  - python=3.7
  - scipy
  - sphinx
  - sphinx-autoapi
  - sphinx-toolbox
  - tqdm